# https://docs.github.com/en/actions/quickstart
name: Continuous integration
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Build and test
        run: yarn run build

      # - name: Run tests
      #   run: yarn test
